import { Inter } from "next/font/google";
import "./index.css";
import Navbar from "@/components/Headers/Navbar";
import Footer from "@/components/Footers/Footer";
import { CartProvider } from "@/contexts/cart";
import { ModalProvider } from "@/contexts/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div id="modal-root"></div>
        <CartProvider>
        <ModalProvider >
        <Navbar />
        {children}
        <Footer />
        </ModalProvider>
        </CartProvider>
        </body>
    </html>
  );
}
