"use client";

import "./index.css";
import Navbar from "@/components/Headers/Navbar";
import Footer from "@/components/Footers/Footer";
import { CartProvider } from "@/contexts/cart";
import { ModalProvider } from "@/contexts/modal";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Food Service",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body>
        {/* <body className={inter.className}> */}
        <div id="modal-root"></div>
        <CartProvider>
          <ModalProvider>
            <Navbar />
            <div className={`${pathName === "/" ? "bg-main" : "bg-white"} min-h-[700px]`}>
              <div className="container mx-auto">{children}</div>
            </div>
            <Footer />
          </ModalProvider>
        </CartProvider>
      </body>
    </html>
  );
}
